### ISSUE TITLE
how to git-clone an app

### ISSUE THREAD

**Issue by oupala** [ecarre-dockerfiles/rhc#2]
I'm trying to git-clone an application using rhc in a docker container.

``` bash
>rhc git-clone kanboard
RSA 1024 bit CA certificates are loaded due to old openssl compatibility
Cloning into 'kanboard'...
ssh: connect to host kanboard-mydomain.openshift.internal port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Unable to clone your repository. Called Git with: git clone ssh://54636d4dc3215ee45e00377f@kanboard-mydomain.openshift.internal/~/git/kanboard.git/ "kanboard"
```

How can I check if the environment config files are really used?

I created a data volume container using the following command:

``` bash
docker create -v /home/myuser/.openshift:/root/.openshift -v /home/myuser/.ssh:/root/.ssh --name rhc-data ecarre/rhc /bin/true
```

But I'm not sure that the config file `/home/myuser/.ssh/config` is used (we have a particular network configuration that require to enable a tunnel to join the openshift platform.

**Comment by emmanuelCarre** [comment]
Hi,

You can verify your configuration with this command (use same image but launch bash instead of rhc):

```
docker run --rm -it --entrypoint=bash --volumes-from rhc-data ecarre/rhc
# then inspect your configuration
vi /root/.ssh/config
```

Below, the test I had done and my ssh config is fine.

```
[ecarre@linux ~]$ docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        
 OS/Arch:      linux/amd64
[ecarre@linux ~]$ docker create -v /home/ecarre/.openshift:/root/.openshift -v /home/ecarre/.ssh:/root/.ssh --name rhc-data ecarre/rhc /bin/true
[ecarre@linux ~]$ docker run --rm -it --entrypoint=bash --volumes-from rhc-data ecarre/rhc
```

Which OS is your host? In case Windows or Mac, be careful when you share host file system to VM, VM to container.

**Comment by oupala** [comment]
Great help @emmanuelCarre ! I managed to check my configuration... and I found a marvellous buggy case!

In fact, my .ssh/config file is a link to another file located into `/home/user/documents/conf/ssh/config`. The **real** config file was then not readable inside the container. Is there a way to tell docker to follow symlinks? Or is it not in the docker philosophy (of containement)?

With a correct `.ssh/config` file, I have a new (_real_) problem: my ssh configuration tells to use `proxytunnel` but proxytunnel is not available in your image. Do you think you could add it to your image?

**Comment by emmanuelCarre** [comment]
About symlink, is not the good way. Furthermore, I used data container because I did not want share my host file system. In your case, you can don't use data container and add files and directories. See [Mount a host file as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-file-as-a-data-volume) and [Mount a host directory as a data volume](https://docs.docker.com/engine/tutorials/dockervolumes/#/mount-a-host-directory-as-a-data-volume)

Yes, proxy is common in company, I will try to add necessary to my image this evening (UTC+2).

**Comment by oupala** [comment]
I'll use data container as you do, it seems cleaner to separate host and container data.

I'll test the image with `proxytunnel` as soon as it is available.

I think I will need to declare another volume (as a workspace) so that the cloned app is available on my host.

**Comment by emmanuelCarre** [comment]
I have create new tag `1.1.0-proxytunnel` (I will add documentation in some days). 

Sorry, I don't have use case, so I just call `/opt/proxytunnel-1.9.0/proxytunnel -h`. Can you check if it OK?

Use it like this:

```
docker run --rm -it --volumes-from rhc-data ecarre/rhc:1.1.0-proxytunnel help
```

**Comment by oupala** [comment]
I tried to _git-clone_ with the new image but I had an error:

``` bash
/bin/sh: line 0: exec: proxytunnel: not found
```

I think that proxytunnel is not in the path.

``` bash
[root@bef9ba8c9938 /]# proxytunnel
bash: proxytunnel: command not found
[root@bef9ba8c9938 /]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[root@bef9ba8c9938 /]# /opt/proxytunnel-1.9.0/proxytunnel --version
proxytunnel 1.9.0 (rev 0) Copyright 2001-2008 Proxytunnel Project
```

Why don't you install proxytunnel via yum, as all other binaries? proxytunnel is [available](https://pkgs.org/centos-7/repoforge-x86_64/proxytunnel-1.9.0-1.el7.rf.x86_64.rpm.html) as an rpm package and should probably be installable via yum (I'm not sure, I'm more a debian user).

**Comment by emmanuelCarre** [comment]
Sorry for mistake, I forgot `make install` command. It is fix into `1.1.1-proxytunnel` version.

RPMforge is abandoned project and I dont found repository so I build it.

**Comment by oupala** [comment]
Great progress! It almost works!

``` bash
>docker run --rm -it --volumes-from rhc-data ecarre/rhc:1.1.1-proxytunnel git-clone kanboard
Cloning into 'kanboard'...
Via tunnel.proxy.internal:443 -> kanboard-mydomain.openshift.internal:22
Enter passphrase for key '/root/.ssh/id_rsa': 
Your application Git repository has been cloned to '/kanboard'
```

The last problem to fix is that the app is cloned on `/` in the container. We have to find a way to clone it somewhere on the host filesystem. I don't have any idea about that, sorry...

**Comment by oupala** [comment]
I've found a solution that allow to `git-clone` an app in a local directory.

This solution requires a modification to the Dockerfile of `rhc` (or maybe `rhc-install` in your case) in order to add a `WORKDIR` directive, such as:

``` Dockerfile
WORKDIR /git-repos
```

Then update your bash alias (and the README file) to:

``` bash
alias rhc='docker run --rm -it --volumes-from rhc-data -v `pwd`:/git-repos ecarre/rhc'
```

Last question: do you plan to merge the proxytunnel branch into the master branch?

**Comment by emmanuelCarre** [comment]
No, I will not merge it on master. I have an other request to use [corkscrew](http://agroman.net/corkscrew/) instead of proxytunnel. I will leave master without proxy tools and use branch for each tools.

I add missing tag for 1.1.1-proxytunnel on my source.

I will update README to use proxytunnel this weekend.

**Comment by oupala** [comment]
Ok, as you want.

I don't think that branches are meant for managing features, but that's your choice.

I tought that having a unique image that can handle all usecases would be a better solution. How would you do if you have to use rhc sometime with proxytunnel, and someting with corkscrew depending on where you connect from, there won't be any usable image and you would have to switch permanently between these two images.

I think your main argument is the final size of the image. Right?

**Comment by oupala** [comment]
Do you think you can add the `WORKDIR` parameter in **all Dockerfiles**, so that we can deal with data on the host drive, as explained in [this comment](#issuecomment-243140751)?
